aws_access_key_id='ASIAZMDKLBE2WRW3IX77'
aws_secret_access_key='vXIcJ2n7PgXyjotqd5CxVaZRLOo7oVcjBXAIaIEt'
aws_session_token='FwoGZXIvYXdzEP7//////////wEaDKzHDNu6MABHcYqgvCLaAeHUD1bdrA1uh+ZfMkjYSAlZUyjrtFsgLaNqsqw0yUEgVXOt+3CZpaEpnQWvD0gDOG93vWybn+vLWMCTtZA5QDETwyIlaaAudmPgl4UXzWbMtgyvJU2zGrrSHE1mNhK2CZ8RqnAWRAWkBQHUac64ic/U9M0ZQnL6NRZPUsumWFuDdL2v9EXnxwScar4WLtBdoimAz34DBnDL4VUQQodLynVRggGtDJnAoy4Y7lJscH7kb5FPIbMgek5Ligx/SVlrLYWY/pieE2lKPik+/SkkZ8aueNbV9Sc0akSwKLKIwvsFMi0XeDIJ3au2uj2IsJNrA+FbLB4duGHBlmWp2GG3IUorpCs1szrnuDf4WqmkjBQ='

aws_default_region = 'us-east-1'
